name: Github Actions

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack with dotnet
      run: dotnet pack --output nuget-packages --configuration Release
    - name: Authorize Omega365 NuGet feed
      uses: StirlingLabs/GithubNugetAuthAction@main
      with:
        owner: vilius@omega365.com
        name: Omega365
        token: ${{secrets.O365_NUGET_API_KEY}}
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.O365_NUGET_API_KEY }} --source ${{ secrets.OMEGA365_NUGET_URL }}
